spring.application.name=greenlog

spring.datasource.url=jdbc:mariadb://localhost:3306/greenlog
spring.datasource.username=root
spring.datasource.password=vibinjoshwa01

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

spring.thymeleaf.cache=false
