spring.application.name=GreenLog
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/greenlog}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:vibinjoshwa01}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
